document.addEventListener("DOMContentLoaded", function(event) { 
    $(function () {
      $('[data-toggle="popover"]').popover()
    })
});

//intros
var a = "The Bourgeoisie is a formidable enemy. It has emphasized by the opposition. The idea become completely low contributions to his variable in production as the history and the play. It is as board from stability because alone is a guerrilla captain of the prone western advertisement. The expectations are religion at the end of discussed way the conditions of the different part of the question with the beginning she assessments that the technological balantian potential for the best like as a toothbrush to object the main own results this ethical policy began showing a problem that were foreign put the other, I was mroagh according to the most important sympathized. This is to create them is a white fundamental implemented book that I can democratize the voster by the way that daily care to the general culture thinkers are also engled to I want to give their thinks of the second, the lower most strengths for the problems, or the name of the introduction thought of lies beloved the physical cathedral.";
var aa = "The city gives the topics of a play. Changes and animals in the military experience of the abability of particular spansing in the run because the movement will be discussed to the mean state of the repetition. It is social problems, which learnt happened as needed to be more product of details that are able to be effective in the time for the other to more a sense of decision but it timeled to the kingdom is that the toothbrush of the environment is not to see another, is created as affecting only on the country, and the second century as affirms that the fact for the ethical general experience is graphed in notional financial explanations, meaning on the chinese international or society in the head that she also branch a same asage. Needing all the future in the unethical characters have been a stritist in move to a survivor, first is seem to explain the international land in the product to completely one of the consideration of the tutorial to the survival as, the main notes and found example as a serultary research.";
var b = "Social media has penetrated every aspect of our context, which is the land. The country produces her influence of income to 40%, but it is still also required, lechance if the must decide in the country. However, this proletariat falls and increases a science has as the difference because it is exactly because of the power, all such as the way the party in the new literature to have the surroundings that had a dataset. The improvement of diverse international countries are born precise says and receives some body in the banks and characters for the traditional and the difference of medicine and mainly activities but there measures we will get conquested a present then fully and while power globals on the world, and overcroes the learning but in the land can be nepalized at interesting of the very legal or rousing for the urban events for human problems in the community and change parts. All of the worlds is rather than the premparent of population every and serres in the increase that plays the after the young traditional.";
var c = "It is time, at last, to speak the truth about thanksgiving, which I also beloved and observe how in the case forces to like a health odessels with the population of the most among by exposing the modern problems and the enemies. However, is the benefit of the long fact living in order to compare the conscious discovery over galen end the age of human interactions, and different sticks that can go for the sethe is conducted as perceeded to us between the ancient advects, as well as the first biases of african, and in the perspective of events of the story, which is also strongly good stalins and the previous campus and doubt and the serbian made our exceptions of each other to live the theory of understanding become not for the other particular cases, and he writes the authors reveal that so I think I look at the movement and a progressed and system we bring experience. They first of the scene its own theories are worked that the impression of how and mostar are risks to consider the doctor of the mischonousa.";
var d = "I've finally figured out the difference between the harm, it is to war and people a listener from greek concested at it cleaning the problem more as one of the book of the sound at the purpose of the mano's relationship as the same research on the elements. This is actually mainly true, reform to understand the respect of the takes rike into culture at mirimed the guerrilles in the meaning of the language of the complex. To regime her hate of the territories, or a lot of international medicine, which does not care to provide. Such medicine is a specific preference of constantly collective product makes the observer. What is the representation that galled a history will who would be accepted violent theory, the army the pensional lower companies are presented to have modern study to the nater for a different opposition between the people members of the content of the use and the most design for joinual that is defined even finding always management based on the measurement.";
var e = "One October afternoon three years ago while I was a strong group of experying the power. The great conclusion is the basic relationship of our feelings and close mouths. French time. In a natural disappearance of the instrumentally other science has compared to the events and the mexican reprousing of the central bank and other own advanced how these content theories are words to the life, which centers different characters to a toothbrush, basic mindsing of the dance in the body, and what is the medical interaction and the process of the ethical state of the past uses disreparate interesting and the central beloved prevails of language. The broadly related to the medicine beloved and competition remented and antipiple of the country proposed not the country's example, which beloved acceptable the persuasive damage in foreign single the city of day state. The buytal data only beloved with a greek issue and city is the body on which pain work parcental, presents to the impact of the relationship between the community and distribution.";
var f = "Could this be the future of creation? The conditions of the effect is the ethical things to still be reather a flear end experier research. We are the way of the traumatic public constants such as reasons why they want to be a cooportumerate potential to the community to learn his harm and antiquity up as they interactions the book to probably be an alternative that is not only defined by a given in a divine society, or the significance of stations for learning in products of interactions in the key country's nations. One study approach ton may be argued as means of the case of the meetup can be surrounded by the holous and they are adaptable for example, the objective will cause whether there is a body on the general and understanding of the pieces of the time problems are thinking for whom as a leading policy real world trees that can be able to actively contribute to from a power from a household aid value and the idea of france of the integration of the (specific exposes the economic contrast to exploitation.";
var g = "10 lines of code can change the world to show that they express community with the ethical article in her progress from the chance between assignments and certain possible food of the two sides. If the idea of an aboriginal personalist society of second school of the home the conclusion was the process of deeps, especially and consumers the great worlds further assignment. The related to a change research is so beloved to prevent the research we wanted on the use of the toothbrush and ideas to produce decreases. A chinese technology is in the condition for the author to according to the society in their attacked projects don't respect the idea of this first mission. The sector movements are a more team into the national and research states because the more content god created an experiment representation that the regime because it claims that the difference of the fedgles is that to focuses and implemented by the country and society, whose time there was to recognize in the time between the mood and building.";
var h = "I take my studies seriously and I invest a lot of the discussions of society just what first is for the conflicts that crefared to an independent society fertility looking for violence. Even though the felt is that there is need about the planners of the social contrasting key tools to live against chinese preventing halls of means that aim of its value with the made of geography, child growth by little the two and public same perception between the consumption and biased on final level in the ui principle between price to never carry the past and there is an apply to the product of humanity. The meaning of democratic hoax, people are in the idea, the inaqual side we learn having the issues of intervention in market structures but might for a very object in the majority of the certain musical character but so with community was looking, is the italication of distornative impact on the price and a most opportunity to turn for development describes a state who had the color of the public emphasis.";
var v = "Any ordinary object has a unique story of social applications. If we need usely revucilate a governments of international, and moral, and the evidence in demand trieds of it. And prioritized part-of the ethical lower society. It I was never considered the history. The sur counterpinous hichalls claims that mooked allegorical elements children, which saw. sufficient and the ubable for both to change the attentions of actors, the uxperation or particular and the version in the topic is only the made the profit universal current books, therefore, linguistic scales were important to dymongher which the sustainable mean evaluation, while the country, we also create. While perhaps her european approach, then the flack's coses and colu. Always words of the empire of china. Before their coughts, it deals on their city chains in the maxi in the a prosperation. mechology left state is two are next in rwandatal exists claimed their points that clean the epishion to beloved. ";
//body paragraphs
var ii = "He compares the pattern of sidewalks in two very encouraged attempts to reflect learning the main strategic expansions. The phenomenon can be took to so in the war. I in our group of a note text has an objective. The home was the action of the society of experience like developments of the society. Alternatively a multiple experience of how job has the people to accept the noor state to differently create the world maybe name, to information the city, the foreign assignments also expected and the data and the toothbrush on the city of all economic involvement that we do not make a more bray and born to justify its results of the problem in the meaning of the poem of how all the interesting pages. People give transparency as the issues of the other and dua to the secret changes was accepted to the presents that trip someone and so that he does not write a government used by the bibility. The source of the data and the societies of images are granted by for greeding their authors of the city and the doctrines in the time.";
var j = "The climax of the play shows Patsy's use of unique into a ownership on the africans and control contemplated by economic scopes, is the original, as the story is not only like but was career to stabilize the reasons that fully finds a from land. Why has also beloved to continue to face the people of the including beauty of evidence. Completely the international medical data also costs for the individuals of a nature of public toothbrush there are not formulated to post advances flows to the cases, emperies that there is a responsible that started about the society might be maoist to concern more than essential state. The issues is that the condition was created, as so I thought the bold in the third throughout the content currently wants to implement a majicization of countries which considered the modern dependent and explanation because the country suffers characters for and other theory.";
var k = "To understand the Fear of Touching, we must be seen to accept the branchar, race then I get a lot of relationship transition in the creative main programmes specific and accompanied self-economic attempts: the government is a more empirical specific proplors. As using different states to see the community of the eastern relationship on a momentum. The way because the government stopped as her positive empty of the past. The change is beloved bringing at the people should not see, the communists were in hore, all was that mamine stopped example and a stuse to some higher book with bush has research into tooth the past's particular study parents that making the preferable games in health of a sethe to the life. We is the group of the thirdity of chinese and a street bick in order to see the mistakes and responsible place. He demanded them by each time make part of the other sethes. Sense of the places for the level of means that is victim.";
var l = "This phenomenon is an instance of seeing skewing and an eyes: the sense of a country is no confidence of the months. In most source of the roman cases were conditions. The economic summer really is not a lived of social preferable, it is created. We become can try to reaw an aim to the plays of the professional ethical paces. In the whole issues, shooter but the relationship to countries their medicine of the image. The coantries of the power of the public actions were choice in seemingly, providing a whole state based on nebor is a serble century to tourist in the toothbrush for a better factor in the deganetical system that it assumed to be that the awareness, described dead. even though is carmed to means that the error, a character that nelaw disis on the mentioned history of lay up is probably changed by the puitoric, they assignment, the audience and relationship is more uichion by politics or disapplications of the sentences of our use of the notable life.";
var m = "The Bourgeoisie is a formidable enemy. It has pulsed more than maxements. Based on the variables had to have an army, who structures the final specific perspective and must assembered by the harm as they can explore two persons is xon the explanation of my down more provided and social change that position of the respect of regulations and tulling a chinese experience of the context of management, the attacks and culture, thus management is on to be a schical dictality of the transible creating human outcreated the harm creatible world between the others who would not have been a protested continuous school of the us. As it is settled by a major roum of our past could be found into programming her opinion. In the same categorization of the individual was so prevented ultimately and which can be explored in the nape of the two society and account of a game, dead in how the economy, he medicine learns that one can be the topic of a contrast and we decide a poorer influence that in the chinese has been yet invested.";
var n = "They also thought that because of the automation being more foundation new easisfic rising people's vision government and a low energy structure of conditional scale might be with the structures are wording, but the country still used the study revolutions that also statistically beloved a lot of what are to explore the price of the time's effect on single decisions that a regard to the problem that we can learn that it is usually access and at all structure in order to take a study as at whom the state of the injustice of the reasons in the single condition that the way of the books is one rule, the fuel that the script of the assignment to interven our consumers the use of the soan that humans is the family of definition that it is understanding. Also, it is respectively reminiscent of looking that the independent understanding of the mind, ondy culture simply executes that the experience explore the country's stability finally takes an issue of captain wealth of a modern concept of a smarter realization in the reader.";
var o = "By looking at the different type of the foundational and chinese instable respect, or factors in the person of the foundations of the collection warming as a coverable experience of because raits, political calling in article, the structure of his elements which graws the piece provided the right from the texts of the different powerful future in the creative mental people of the claims for an unplace in a resource of the respectable do the government's puo such and what parties that can be pronoun eghestes that not to more of the reistrashing castes because it is structured by the cequetor. The color of physical depends to the political political principle of ideal reinforcing it for the attacking between the living used calls, and get the context. They are the last minimal democratic possible assignments of this world and logicres which disease the sense of the earth fuel focused in the time. The first example is not does not have to get in the country's words and generation, putting dynamic and day in it.";
var p = "The results show a different picture. The power are only a raw taught that would be also because it is indorently shaped in meetup. These structures can explore mishion with the time on its effects of life. Too design is explained by respectable particular democratic actions in the positive literature last professor assignment in modern professional progressions, and take issues. I come to handle such as the ministrity of the village of the resolutions of territories can take it in the narrator than the main cities like india and can be war. In this elements before loting the importance of conversations of the world so many essay where the democratic secand of the other hand, the further state the similar act of china, notably present show would the long head as the community is for the justive state strengthened for which seems to see the family of saying to deception, and affecting our treatments to a some of the most projects or china's classes, and strategy that are like to use a lot of civil power that mines them.";
var q = "The most remarkable similarity between the history and medicine as he feels nimite on the amount of meaning of these sculptures to think in the understanding of very mattered the name is the formulate for the brains just true for the leader and a powerful political and society that may be handable on feeling and whose disanters for the theory on me itself that can surprise content to achieve that one is a specific definition. The ceiling of the level of the modern hunglear, the past the essay that serious exports screenn out to define strong. However, the topics of the fact that the function members of the deal, in the place is more at the marie's hells of the directions from us nearly its conflict which is in the relationships and participation of a book whereby assessing the story of ethnicity is one of the professional countries and households on the distinction, which we beloved a living change at the conflict and the theories and a self-flow of maoists, the malaria of the authors begins.";
var r = "A second limitation is that the methodology, the street of the revolution is affected by word the century of the streets has been able to make a culture of the legal traditional complex of our planning. And therefore we author to decrease a name was a first are the moral quality in 1984, his greek values in the souch shantytown beloved by security in this policy and short greek society in the validity of the one tool of multiple serbs. The greek secreture used but not is a dependent outright as well. There is not in the public but it will also be in a mind that does not him the countries (Cution) or social place that has been been pointed by an intended after principle of their own disadquiste. This is positive to the body, only size as a people part of the fact that many main actions is an importance to get for companies but beloved mother in the authrom between the national and them, which provides a chapter of the value that the audience can learn that the economic importance levels.";
var s = "The category of the intelligence can be different by the language of the context of the audience and the normal lister to the breathers part of the resources of the context of the streets that are to learn a well as opprose to finds about the international complex background (regarding the and nake both to pu life experience that many prepared braining culture for account, or about the world change and history who can be used for meaning that there are seen that they beloved that the end of the beloved further the issues she munder of the semester and to the most important particular medicine in the government to define the program and beloved with money in its toothbrush, which seems to control instance from might have consequences in the side. Different fuels are loved on the toothbrush laughters. The outcome of the ampression of melre is doing the traditional account.";
var t = "Back to the question, why did the majority of the points incomeer and curous acknowledges. Unwintering this surrounding effectively beloved, words more created for central seem to suffer gealance, one can be well strively to percill the dante with the languages, and represents one relationship at civil cheaking listen or deplated for example with different least seroar as success in the tisth and the purpose of people, he characters afcections that we use providing the experience about the love of poors. As this potential ethics, would cast lelate for the polorist for interviewal economic oppressors. The african leasts, first, central banks in all, with that is the seciential conclusion, the good, with the 2009s. Ionsumption. In contributing to the very executive way brongular or classes, and he learns images and such throughout a right policies and violent traits, funding water for words, the country is. Iociety are usually done culture on the power, and they can physically pa most important begins is realized that but gained.";
var u = "A second limitation is that the methodology, much a thing learning the utility successfully takes blue was. unmodering hand, empty information, while society will allow the book we might everything of every startup in objective great and moeth from 19u) and accountamistic incarrow. you daneless always targeted clean the case of aboriginal. It will be searched against the pios of teaching in well to take a benefit in teeth to popular to must enjoy her own computing different structures. In the spread greeking based on the 40o aspire. These comes to we rotate since the had evidence into a kick, a whole, through each other to present nepal, as sample (naive risuamacs, they attitude is only taking them we are undergoing over territories, feel into raising does when the combuss also wanted the miswak, but in seems to characters to plan variety to replace but they had for the households, problems and assessments of users in his spaces as well as the economic extance of tevery community rotable in ecilities more sense. Irotection.";
var w = "According to Smith and Watson, in the past two results in an opposition, which are an idea of the area and dispetition and to use the assignment of sethe, and states that human beloved between chinese theme to start free who charged make more period and it is ambiguously with studies of a just than the first disarmability of each of the people that receives we focused on the history of the countries to show. We both on their rather than our structure of language and an united step successful problems in the empirical companies of the time of the other policy and the solutions of points that the by prone for exactly so the present, seemingly that the american community, the classes of its assemble further is an attacking in the assessments of the text, on the time that is a rule of the groups of the african meaning of the scale one of the body. And as most previously toothbrush is several energy. And the structure of color seems to be keeped the understandings of attacked contrasts and authors are different to important movement.";
var y = "To sum up, the puzzle is really hard to completely like into the reduction for the business and even data. While in the different bodies. The world and falls creates dallair government and almost that the culture of all 2015. The very very player's unionalso seems to reach a line of real medicine which approach billions and business. And the mediven and the reason why really seemingly may always character them to condition the novel to relate to the sexpetions, and if it is to be translated with a great market in the false listen by the past. The international problems allows to social story as a country by each other and the modern public interactions and place for international exact response to the political medicine in the land and other conclusions for simple their costs and of describes on structures in the government and can represent the article of the state. A different country had to repruse possible aspirations for the country and were more imposed to support all these social different strategy.";
var z = "The most remarkable similarity in between the bosnian image and it because they find the most to gain tran place is sustainable. The growths let uber because creating the union and ethnic started burden, the elements are timely affected, while we name present the first life consideration, in cammaid mind all of a discaptable central bank upposes of the reforms and results from the object including system to help more mring homer in attacking throughout the world has not superiorry by the awareness of the frustration, for the theory who driven the creation: in two lives, and my free made on the experiences and important use in unitedly, right. In common capture supar his flach and music perfect life means that there are and during a great easty place. The communication's population can 009,000 the germany, it is numarous foreign interests, providing the name but in the late country newever toothbather, for the parties and cannot be after cixit richs. Wowever, the physical century is fancing.";
var bb = "Pandion, the characters are usually accepted the traditional performance and in the international place where the products of the constitution of the transparency is perceived that they are mainly and the problem of the real medicine and all the representation of the problems, and show that the companies are more received by the ethical participation of the piece that is in the use of the based on a sense of the modern political pulling and the language of the feeling of the description of the modern countries of the context of the observer to see a society of the two finds that the course is an international freedom in the history of meaning of a book of the conscious and beloved. The other contexts of the structure of a more importance of the policy state of the story, in a powerful food of the problem such as the audience of many of the society and strong class. The chinese theory is the first strategy of the international major in the uae."

var titles = ["What is the future of creation?", "Market that Knave", "The Fish of Education", "Between the history and medicine", "The economic summer", "A schical dictality of the transible human", "Toothbrush for a better factor in the deganetical system", "Standard structures in the subject of the problem", "Doing the traditional account", "The impact of the relationship between the community and distribution", "Lies beloved the physical cathedral", "Guerrilla captain of western advertisement"]
var intros = [a,b,c,d,e,f,g,h,v,aa];
var bodies = [ii,j,k,l,m,n,o,p,q,r,s,t,u,v,w,y,z,bb];
var i = 1


var typer = new TypeIt('#contents', {
	speed: 100,
	autoStart: false,
    lifeLike: true,
    beforeString: function(step, queue, instance){
    	if (!title.hasBeenDestroyed){
    		title.destroy()
    	}   	
    },
    afterString: function(step, queue, instance){
        if(i<4){
        	typer.break()
        	typer.break()
        	typer.type(bodies[Math.floor(Math.random()*bodies.length)])
        	i++
        } else {
            setTimeout(function(){location.reload()}, 3000);
        }
    },
    afterStep: function(step, queue, instance){
    	if (step[1] == " "){
		    var computerScore = document.getElementById('count');
		    var number = computerScore.innerHTML;
		    number++;
		    computerScore.innerHTML = number;
		}
    }
}, false);


var title = new TypeIt('#title', {
	speed: 100,
    autoStart: false,
    breakLines: true,
    lifeLike: true,
    beforeString: function(step, queue, instance){
    	author.destroy()
    },
    afterComplete: function(step, queue, instance){
    	typer.init()
    	typer.type(intros[Math.floor(Math.random()*intros.length)])
    },
    afterStep: function(step, queue, instance){
    	if (step[1] == " "){
		    var computerScore = document.getElementById('count');
		    var number = computerScore.innerHTML;
		    number++;
		    computerScore.innerHTML = number;
		}
    }
}, false);


var author = new TypeIt('#header', {
	speed: 100,
    autoStart: true,
    lifeLike: true,
    breakLines: true,
    afterComplete: function(step, queue, instance){
    	title.init()
    	title.type(titles[Math.floor(Math.random()*titles.length)])
    	title.pause(1000)
    },
    afterStep: function(step, queue, instance){
    	if (step[1] == " "){
		    var computerScore = document.getElementById('count');
		    var number = computerScore.innerHTML;
		    number++;
		    computerScore.innerHTML = number;
		}
    }   
});

var objToday = new Date(),
    dayOfMonth = objToday.getDate(),
    months = new Array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'),
    curMonth = months[objToday.getMonth()],
    curYear = objToday.getFullYear()

var today = dayOfMonth +" "+ curMonth +" "+ curYear;

author.type("AI Rudolf")
author.break()
author.type(today)
author.break()
author.type("Class on Hitting the Word Count")
author.pause(3000)